### ISSUE TITLE
How would you remove all unit test packages and code from publish directory ?

### ISSUE THREAD

**Issue by nagtilaklaxman** [matthewrenze/writing-testable-code#2]
If you add unit testing libraries and unit test code inside source project then how would you remove that from publish directory?

**Comment by matthewrenze** [comment]
You can either use compiler directives or pre-processing in your build script to remove any unit test files based on their filename prefix or suffix (e.g. TestSomeClass.cs" or "SomeClassTests.cs") before compiling the solution. 

Or, if you don't have any major size constraints in production you can just leave them in there. They don't really harm anything if you leave them in your production DLLs.

Plus, there can be benefits to finding "Heisen-bugs" (i.e. bugs that don't show up in development but show up in staging or production). However, it only works if you write your unit tests in a way that doesn't modify the state of the running application -- like you should be doing to create a comprehensive suite of fast, parallelizable, and stateless unit tests.

In general, more developers that I've worked with prefer to keep them in separate (parallel) projects. There are pros and cons to each approach. However, every developer I know that has tried both approaches found a lot of value in keeping the test classes in the same project as the subject under test.

It's up to you though. Try it both ways and see what works well and what doesn't.
